using UnityEngine;

public class FirstPersonLook : MonoBehaviour
{
    [SerializeField]
    Transform character;
    public float sensitivity = 2;
    public float smoothing = 1.5f;
    float prevoiousSensitivity;

    Vector3 velocity;
    Vector3 frameVelocity;



    void Reset()
    {
        // Get the character from the FirstPersonMovement in parents.
        character = GetComponentInParent<FirstPersonMovement>().transform;
    }

    void Start()
    {
        // Lock the mouse cursor to the game screen.
        Cursor.lockState = CursorLockMode.Locked;
        prevoiousSensitivity = sensitivity;
    }

    void Update()
    {
        // Get smooth velocity.
        Vector3 mouseDelta = new Vector3(Input.GetAxisRaw("Mouse X"), Input.GetAxisRaw("Mouse Y"));
        Vector3 rawFrameVelocity = Vector3.Scale(mouseDelta, Vector3.one * sensitivity);
        frameVelocity = Vector3.Lerp(frameVelocity, rawFrameVelocity, 1 / smoothing);
        velocity += frameVelocity;
        velocity.y = Mathf.Clamp(velocity.y, -90, 90);

        // Rotate camera up-down and controller left-right from velocity.
        transform.localRotation = Quaternion.AngleAxis(-velocity.y, Vector3.right);
        character.localRotation = Quaternion.AngleAxis(velocity.x, Vector3.up);
    }

    public void DisableLook()
    {
        sensitivity = 0;
    }

    public void EnableLook()
    {
        sensitivity = prevoiousSensitivity;
    }
}
